groups:
  - name: test-alerts

    rules:
      - alert: AlwaysFiring

        expr: vector(1)

        for: 15s

        labels:
          severity: warning

        annotations:
          summary: "Test Alert"
          description: "This alert is used to verify Alertmanager connectivity."