services:
  prometheus:
    image: prom/prometheus:v3.5.0
    restart: unless-stopped

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/data:/prometheus

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"

    networks:
      - observability

networks:
  observability:
    driver: bridge